packages:
  - mari-puntos-app
  - mari-puntos-backend
  - mari-puntos-website

allowBuilds:
  '@clerk/shared': false
  '@scarf/scarf': false
  '@sentry/cli': true
  browser-tabs-lock: false
  bufferutil: true
  core-js: false
  esbuild: true
  unrs-resolver: true
  utf-8-validate: true

minimumReleaseAgeExclude:
  - '@clerk/backend@3.16.13'
  - '@clerk/express@2.1.64'
  - '@clerk/shared@4.30.2'
  - morgan@1.12.0
  - zod@4.5.2
  - '@expo/cli@57.0.20'
  - '@expo/env@2.4.3'
  - '@expo/fingerprint@0.20.11'
  - '@expo/metro-config@57.0.12'
  - expo-constants@57.0.16
  - expo-font@57.0.2
  - expo-updates@57.0.19
  - expo@57.0.18
  - '@clerk/clerk-js@6.30.2'
  - '@clerk/expo@4.6.1'
  - '@clerk/react@6.14.8'
